# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Issues
on:
    issues:
        types:
            - opened
jobs:
    issues:
        if: github.repository == 'alexrp/zig-msbuild-sdk'
        runs-on: ubuntu-latest
        steps:
            - name: Label issues
              if: github.event.action == 'opened'
              uses: github/issue-labeler@v2.3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/issue-labeler.yml
                  enable-versioned-regex: 0
